name: ${name}
version: ${version}
main: team.idealstate.minecraft.spigot.fastcommand.FastCommand
author: ketikai
load: STARTUP
depend:
  - minecraft-library-loader-spigot
libraries:
  - team.idealstate.hyper:hyper-command-impl:${hyperCommandMajorVersion}